// goal: manages high-fidelity audio processing in the offscreen document via tab capture streams
// eff: constructs a complete WebAudio graph: Source -> Gain -> Bass -> EQ -> Comp -> Panner -> Delay -> Analyser -> Dest

import { AudioParams, CompressorOn, CompressorNativeOff } from '@nexus/audio-engine';
import type { AudioConfig } from '@nexus/kernel';
import { OffscreenActions } from '@nexus/contracts';

interface AudioProcessor {
	ctx: AudioContext;
	stream: MediaStream;
	gain: GainNode;
	bass: BiquadFilterNode;
	comp: DynamicsCompressorNode;
	eqNodes: BiquadFilterNode[];
	panner: StereoPannerNode;
	delayNode: DelayNode;
	analyser: AnalyserNode;
}

const processors = new Map<number, AudioProcessor>();

// goal: acts as the primary signal processor for tab-captured audio streams
chrome.runtime.onMessage.addListener((msg, _sender, sendResponse) => {
	if (msg.target !== 'offscreen') return;

	switch (msg.action) {
		case OffscreenActions.OFFSCREEN_START:
			startCapture(msg.tabId, msg.streamId, msg.config);
			break;
		case OffscreenActions.OFFSCREEN_STOP:
			stopCapture(msg.tabId);
			break;
		case OffscreenActions.OFFSCREEN_UPDATE_CONFIG:
			updateAudio(msg.tabId, msg.config);
			break;
		case OffscreenActions.OFFSCREEN_GET_VIZ: {
			const p = processors.get(msg.tabId);
			if (p?.analyser) {
				const data = new Uint8Array(p.analyser.frequencyBinCount);
				p.analyser.getByteFrequencyData(data);
				sendResponse({ buffer: Array.from(data) });
			} else {
				sendResponse({ buffer: null });
			}
			return true;
		}
	}
});

// pre: receives a valid streamId generated by chrome.tabCapture in the background
// eff: boots the AudioContext and serializes the functional processing chain
async function startCapture(tabId: number, streamId: string, config: AudioConfig): Promise<void> {
	if (processors.has(tabId)) return;

	try {
		const stream = await navigator.mediaDevices.getUserMedia({
			audio: {
				mandatory: {
					chromeMediaSource: 'tab',
					chromeMediaSourceId: streamId
				}
			} as any,
			video: false
		});

		const ctx = new AudioContext();

		const source = ctx.createMediaStreamSource(stream);
		const gain = ctx.createGain();

		const bass = ctx.createBiquadFilter();
		bass.type = 'lowshelf';
		bass.frequency.value = AudioParams.BASS_FREQUENCY;

		const comp = ctx.createDynamicsCompressor();

		const analyser = ctx.createAnalyser();
		analyser.fftSize = AudioParams.FFT_SIZE;

		const eqNodes = AudioParams.EQ_FREQUENCIES.map(f => {
			const n = ctx.createBiquadFilter();
			n.type = 'peaking';
			n.frequency.value = f;
			n.Q.value = AudioParams.EQ_Q;
			return n;
		});

		const panner = ctx.createStereoPanner();
		const delayNode = ctx.createDelay(1);

		// inv: nodes are connected linearly; head tracks the output of the previous node to ensure serial processing
		let head: AudioNode = source;
		head.connect(gain); head = gain;
		head.connect(bass); head = bass;
		eqNodes.forEach(n => { head.connect(n); head = n; });
		head.connect(comp); head = comp;
		head.connect(panner); head = panner;
		head.connect(delayNode); head = delayNode;
		head.connect(analyser);
		analyser.connect(ctx.destination);

		// rule: browser policies often start contexts as 'suspended'; explicit resume is mandatory for playback
		if (ctx.state === 'suspended') {
			await ctx.resume();
		}

		processors.set(tabId, { ctx, stream, gain, bass, comp, eqNodes, panner, delayNode, analyser });

		updateAudio(tabId, config);
	} catch (e) {
		console.error('[SPECTRA] Offscreen capture failed:', e);
	}
}

// eff: stops all stream tracks and releases the AudioContext to prevent memory leaks in the offscreen process
function stopCapture(tabId: number): void {
	const p = processors.get(tabId);
	if (p) {
		p.stream.getTracks().forEach(t => t.stop());
		p.ctx.close();
		processors.delete(tabId);
	}
}

// goal: applies the latest AudioConfig to the Web Audio node parameters with temporal smoothing
function updateAudio(tabId: number, config: AudioConfig): void {
	const p = processors.get(tabId);
	if (!p) return;

	if (p.ctx.state === 'suspended') {
		p.ctx.resume();
	}

	// rule: gain mapping: 0-100% -> 0.0-1.0; 100-800% (boost) -> 1.0-8.0
	const val = config.muted ? 0 : config.volume;
	const gainVal = val / 100;

	const t = p.ctx.currentTime;
	const r = AudioParams.SMOOTH_TIME;

	// note: setTargetAtTime is preferred over linearRampToValueAtTime to avoid audio glitches
	p.gain.gain.setTargetAtTime(gainVal, t, r);
	p.gain.channelCount = config.mono ? 1 : 2;

	p.bass.gain.setTargetAtTime(config.bass ? AudioParams.BASS_GAIN : 0, t, r);

	p.eqNodes.forEach((n, i) => {
		n.gain.setTargetAtTime(config.eqValues?.[i] || 0, t, r);
	});

	if (config.compressor) {
		p.comp.threshold.setTargetAtTime(CompressorOn.threshold, t, r);
		p.comp.knee.setTargetAtTime(CompressorOn.knee, t, r);
		p.comp.ratio.setTargetAtTime(CompressorOn.ratio, t, r);
		p.comp.attack.setTargetAtTime(CompressorOn.attack, t, r);
		p.comp.release.setTargetAtTime(CompressorOn.release, t, r);
	} else {
		// rule: apply transparency (neutral params) when compressor is toggled off instead of disconnecting nodes
		p.comp.threshold.setTargetAtTime(CompressorNativeOff.threshold, t, r);
		p.comp.ratio.setTargetAtTime(CompressorNativeOff.ratio, t, r);
	}

	p.panner.pan.setTargetAtTime(Math.max(-1, Math.min(1, config.pan ?? 0)), t, r);

	const delayMs = Math.max(0, config.delay ?? 0);
	p.delayNode.delayTime.setTargetAtTime(delayMs / 1000, t, r);
}
